# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_auto_20161001_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalcriticaltransaction',
            name='account_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='internalnoncriticaltransaction',
            name='account_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
