ACCOUNT_NUMBER_LENGTH = 17
ACCOUNT_TYPE_CHECKING = "Checking"
ACCOUNT_TYPE_SAVINGS = "Savings"

ADMINISTRATOR = "Administrator"
ADMINISTRATOR_ATTRIBUTE = "administrator"

BUSINESS_CODE_LENGTH = 9

CITY_LENGTH_MAX = 100
CITY_LENGTH_MIN = 4

CHECKING_ACCOUNT = "Checking Account"
CHECKING_ACCOUNT_ATTRIBUTE = "checking_account"

CREDIT_CARD = "Credit Card"
CREDIT_CARD_ATTRIBUTE = "checking_account"
CREDIT_CARD_NUMBER_LENGTH = 16

EMAIL_LENGTH_MAX = 100
EMAIL_LENGTH_MIN = 3

INDIVIDUAL_CUSTOMER = "Individual Customer"
INDIVIDUAL_CUSTOMER_ATTRIBUTE = "individualcustomer"

MAX_BALANCE = 9999999.99
CREDIT_CARD_INTEREST_RATE = 0.03
CREDIT_CARD_LATE_FEE = 15
CREDIT_CARD_MAX_BALANCE=1000
CREDIT_CARD_MIN_BALANCE=0

MERCHANT_ORGANIZATION = "Merchant / Organization"
MERCHANT_ORGANIZATION_ATTRIBUTE = "merchantorganization"

MIN_BALANCE = 0.00


NAME_LENGTH_MAX = 100
NAME_LENGTH_MIN = 2

NONCRITICAL_TRANSACTION_LIMIT = 10000.00

OTP_EXPIRATION_DATE = 15 * 60
OTP_LENGTH = 13

PAGE_TO_VIEW_CHECKING_ACCOUNT = "checking_account"
PAGE_TO_VIEW_CREDIT_CARD = "credit_card"
PAGE_TO_VIEW_EDIT_PROFILE = "edit_profile"
PAGE_TO_VIEW_PROFILE = "profile"
PAGE_TO_VIEW_SAVINGS_ACCOUNT = "savings_account"

PASSWORD_LENGTH_MAX = 256
PASSWORD_LENGTH_MIN = 8

REGULAR_EMPLOYEE = "Regular Employee"
REGULAR_EMPLOYEE_ATTRIBUTE = "regularemployee"

ROUTING_NUMBER_LENGTH = 9

SAVINGS_ACCOUNT = "Savings Account"
SAVINGS_ACCOUNT_ATTRIBUTE = "savings_account"

SSN_LENGTH = 9

STATES = [
    "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA",
    "HI","ID","IL","IN","IA","KS","KY","LA","ME","MD",
    "MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ",
    "NM","NY","NC","ND","OH","OK","OR","PA","RI","SC",
    "SD","TN","TX","UT","VT","VA","WA","WV","WI","WY",
]

STREET_ADDRESS_LENGTH_MAX = 100
STREET_ADDRESS_LENGTH_MIN = 4

SYSTEM_MANAGER = "System Manager"
SYSTEM_MANAGER_ATTRIBUTE = "systemmanager"

TRANSACTION_MESSAGE = "The following transaction was "
TRANSACTION_SUBJECT_APPROVED = "Your Transaction Was Approved"
TRANSACTION_SUBJECT_DENIED = "Your Transaction Was Denied"

TRANSACTION_STATUS_APPROVED = "approved"
TRANSACTION_STATUS_DENIED = "denied"
TRANSACTION_STATUS_RESOLVED = "resolved"
TRANSACTION_STATUS_UNRESOLVED = "unresolved"

TRANSACTION_TYPE_ACCESS_EXTERNAL_USER_REQUEST = "access_external_user_request"
TRANSACTION_TYPE_CREDIT = "credit"
TRANSACTION_TYPE_DEBIT = "debit"
CREDIT_CARD_TRANSACTION_TYPE_DEBIT = "credit_card_debit"
CREDIT_CARD_TRANSACTION_TYPE_CREDIT = "credit_card_credit"
TRANSACTION_TYPE_EXTERNAL_USER_PROFILE_EDIT_REQUEST = "external_user_edit_profile_request"
TRANSACTION_TYPE_PAYMENT = "payment"
TRANSACTION_TYPE_PAYMENT_ON_BEHALF = "payment_on_behalf"
TRANSACTION_TYPE_TRANSACTION_ACCESS_REQUEST = "transaction_access_request"
TRANSACTION_TYPE_TRANSFER = "transfer"

USERNAME_ADDRESS_LENGTH_MAX = 150
USERNAME_ADDRESS_LENGTH_MIN = 6

ZIPCODE_LENGTH = 5
